// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZvUIExJir4Qixx76_TmMJAlgOxV71hzg', // Using Android Key as fallback or placeholder
    appId: '1:963813242008:web:7573f883bb8a64b1764ced',
    messagingSenderId: '963813242008',
    projectId: 'sezen-finmodel',
    authDomain: 'sezen-finmodel.firebaseapp.com',
    storageBucket: 'sezen-finmodel.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZvUIExJir4Qixx76_TmMJAlgOxV71hzg',
    appId: '1:963813242008:android:8c14f883bb8a64b1764ced',
    messagingSenderId: '963813242008',
    projectId: 'sezen-finmodel',
    storageBucket: 'sezen-finmodel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB_ZNGA-XTTfXfX0L_CVf2gCnFwcQk5Q0',
    appId: '1:963813242008:ios:b8f8436ced436073764ced',
    messagingSenderId: '963813242008',
    projectId: 'sezen-finmodel',
    storageBucket: 'sezen-finmodel.firebasestorage.app',
    iosBundleId: 'com.example.finmodel',
  );
}
